# Site settings
title: Free time!
email: 
description: Use seu tempo livre pra assistir palestras	
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# Build settings
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null
exclude: ["node_modules", "gulpfile.js", "package.json"]
paginate_path: 'page:num'
paginate: 20