# Site settings
title: Free time  - Use seu tempo livre pra assistir palestras !
email: andersomxp@gmail.com
description: # add Breve	
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# Build settings
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null
exclude: ['bower_components']
sass:
  style: compressed

paginate_path: 'page:num'
paginate: 20